import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header";
// 1. localFont'u import et
import localFont from "next/font/local";
import Footer from "./footer";
// 2. Fontu yapılandır
const garet = localFont({
  src: [
    {
      path: './fonts/Garet-Book.woff2',
      weight: '400', // Book genelde 400 (Normal) kabul edilir
      style: 'normal',
    },
    {
      path: './fonts/Garet-Heavy.woff2',
      weight: '900', // Heavy en kalın (Black) olandır
      style: 'normal',
    },
  ],
  variable: "--font-garet",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${garet.variable} antialiased`}
      >
        <Header />
        <div className="mt-12">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
